
name: video-api-project
region: nyc

services:
  - name: api
    github:
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    source_dir: /
    http_port: 8080
    envs:
      - key: PORT
        value: "8080"
      - key: HOST
        value: "0.0.0.0"
      - key: NODE_ENV
        value: "production"
    instance_count: 1
    instance_size_slug: basic-xxs
